name: medfe_inner_loss_mask_decoder
mode: train
arch:
  type: medfe
  use_inner_loss: true
  has_mask_encoder: true
  init_args:
    init_type: normal
    init_gain: 0.2
  encoder:
    type: medfe
    name: Encoder
    input_nc: 3
    output_nc: 3
    ngf: 64
    use_dropout: false
  decoder:
    type: medfe
    name: Decoder
    input_nc: 3
    output_nc: 3
    ngf: 64
    use_dropout: false
  mask_encoder:
    type: medfe
    name: Encoder
    input_nc: 3
    output_nc: 1
    ngf: 64
    use_dropout: false
  mask_decoder:
    type: medfe
    name: Decoder
    input_nc: 1
    output_nc: 1
    ngf: 64
    use_dropout: false
  pc_block:
    type: pc_conv
    name: PCconv
  discriminator_gt:
    type: discriminator
    name: NLayerDiscriminator
    input_nc: 3
    ndf: 64
    n_layers: 3
    use_spectral: false
    use_sigmoid: false
  discriminator_mask:
    type: discriminator
    name: NLayerDiscriminator
    input_nc: 1
    ndf: 64
    n_layers: 3
    use_spectral: false
    use_sigmoid: false
loss:
  lambdaP:  5
  lambdaS: 0.1
  lambdaL1: 50
  lambdaGan: 10
trainer:
  optimizer:
    optimizer_type: "adam"
    lr: 0.0002
    beta1: 0.5
  scheduler:
    lr_policy: lambda
    # lamdata |setp |plateau |cosine
    start_epoch: 1
    niter: 20
    niter_decay: 100
  save_epoch_freq: 1
  continue_train: false
  # continue_train的时候需要load epoch参数
#  load_epoch: 0
  display_freq: 40
  print_freq: 40
  save_dir: "./checkpoints/medfe_inner_loss_mask_decoder"
  log_dir: "./tensorboard/medfe_inner_loss_mask_decoder"

datasets:
  train:
    dataset:
      type: AlignedMaskDataset
      args:
        data_root: /data_ssd/ocr/zhoubingcheng/gan_datasets/gan_aligned_crop_data_with_mask_small/
    loader:
      batch_size: 1
      shuffle: false
      pin_memory: true
      num_workers: 16