name: medfe_predict
mode: predict
arch:
  type: medfe
  init_args:
    init_type: normal
    init_gain: 0.2
  encoder:
    type: medfe
    name: Encoder
    input_nc: 4
    output_nc: 3
    ngf: 64
    use_dropout: false
  decoder:
    type: medfe
    name: Decoder
    input_nc: 3
    output_nc: 3
    ngf: 64
    use_dropout: false
  mask_encoder:
    type: medfe
    name: Encoder
    input_nc: 3
    output_nc: 1
    ngf: 64
    use_dropout: false
  mask_decoder:
    type: medfe
    name: Decoder
    input_nc: 1
    output_nc: 1
    ngf: 64
    use_dropout: false
  pc_block:
    type: pc_conv
    name: PCconv
  discriminator_gt:
    type: discriminator
    name: NLayerDiscriminator
    input_nc: 3
    ndf: 6
    n_layers: 3
    use_spectral: true
    use_sigmoid: false
  discriminator_mask:
    type: discriminator
    name: NLayerDiscriminator
    input_nc: 1
    ndf: 64
    n_layers: 3
    use_spectral: true
    use_sigmoid: false
predictor:
  load_epoch: 4
  model_dir: "./checkpoints/medfe"
  long_side: 1024
  out_img_dir: "./online_data/output"

